import Header from "./components/Header/Header";
import "./globals.css";
import localFont from 'next/font/local';

const satoshi = localFont({
  src: './fonts/SatoshiVariable.ttf',
  variable: '--font-satoshi',
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
